### PR TITLE
Add test for loading Secp256k1 private key

### PR DESCRIPTION
**Pull request by aknuds1**
Add test for loading Secp256k1 private key.

### CODE REVIEW

**Comment by aknuds1** [comment]
Fails because transitive dependency on libp2p-crypto-secp256k1 doesn't get upgraded.

**Comment by jacobheun** [comment]
Might be the node modules cache on travis. I nuked the cache and restarted to see if that resolves it.

**Comment by jacobheun** [comment]
@aknuds1 bubbling up the dependencies it looks like there is an issue in master here with a fresh install. Can you take a look?

```log
  1) configuration
       should be able to load a Secp256k1 private key:

      AssertionError: expected '16Uiu2HAm7txvwZbeK5g3oB3DrRhnARTEjTNorVreWJomfHJHbEu2' to deeply equal 'QmaXywut5mxJHYGE2qGht9e6BynFNKrWUwqMgJ6MVE9Q2J'
      + expected - actual

      -16Uiu2HAm7txvwZbeK5g3oB3DrRhnARTEjTNorVreWJomfHJHbEu2
      +QmaXywut5mxJHYGE2qGht9e6BynFNKrWUwqMgJ6MVE9Q2J
      
      at Context.it (test/daemon/config.spec.js:86:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by aknuds1** [comment]
> @aknuds1 bubbling up the dependencies it looks like there is an issue in master here with a fresh install. Can you take a look?
> 
> ```
>   1) configuration
>        should be able to load a Secp256k1 private key:
> 
>       AssertionError: expected '16Uiu2HAm7txvwZbeK5g3oB3DrRhnARTEjTNorVreWJomfHJHbEu2' to deeply equal 'QmaXywut5mxJHYGE2qGht9e6BynFNKrWUwqMgJ6MVE9Q2J'
>       + expected - actual
> 
>       -16Uiu2HAm7txvwZbeK5g3oB3DrRhnARTEjTNorVreWJomfHJHbEu2
>       +QmaXywut5mxJHYGE2qGht9e6BynFNKrWUwqMgJ6MVE9Q2J
>       
>       at Context.it (test/daemon/config.spec.js:86:37)
>       at process._tickCallback (internal/process/next_tick.js:68:7)
> ```

@jacobheun I'll see if I can reproduce.

**Pull request merged**
