### PR TITLE
Fix package.json's main property

### PR DESCRIPTION
**Pull request by aknuds1**
Fix `main` property of package.json.

### CODE REVIEW

**Comment by jacobheun** [comment]
The `main` property is intended to allow the Daemon to be used programatically, which is why it's currently set to `daemon.js`.

`bin` is set to the cli file to expose the `jsp2pd` command on install.

**Comment by aknuds1** [comment]
> The `main` property is intended to allow the Daemon to be used programatically, which is why it's currently set to `daemon.js`.

@jacobheun Thanks for clarifying, but can you help me understand how it's supposed to work please?

1. Should it be src/daemon.js, since this seems to be the correct path?
2. How is the `main` property used programmatically? I'm not familiar with this usage. The reason I issued this PR is that `node .` fails due to not finding daemon.js.

**Comment by jacobheun** [comment]
> Should it be src/daemon.js, since this seems to be the correct path?

Ah yes, that's the problem, good catch. 

Ideally I think we'd have this just be `src/index.js` and then expose some of the other files there. For example, the daemon client is currently requiring the protocol via `require('libp2p-daemin/src/protocol')` instead of `const { protocol } = require('libp2p-daemon')`.

By programmatically I just mean you should be able to require and run the daemon in code, `const Daemon = require('libp2p-daemon')`, which is going to fail because of the path issue you mentioned.

I would expect `node .` to fail to do anything as this should be `node ./src/cli/bin` if you're running it from this repo. Any install will result in you being able to do `npx jsp2pd`, or `jsp2pd` if installed globally.

**Comment by aknuds1** [comment]
@jacobheun I revised `main` to be 'src/daemon.js' now.

**Pull request merged**
